-- Tạo kiểu ENUM cho các trường
CREATE TYPE gender_enum AS ENUM ('MALE', 'FEMALE', 'OTHER');
CREATE TYPE user_type_enum AS ENUM ('OWNER', 'ADMIN', 'USER');
CREATE TYPE user_status_enum AS ENUM ('NONE', 'ACTIVE', 'INACTIVE');
CREATE TYPE payment_method_enum AS ENUM ('MOMO', 'VNPAY');


CREATE TABLE public.tbl_user (
	date_of_birth date NULL,
	created_at timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamp(6) NULL,
	phone varchar(15) NULL,
	email varchar(255) NULL,
	first_name varchar(255) NULL,
	last_name varchar(255) NULL,
	"password" varchar(255) NULL,
	username varchar(255) NOT NULL,
	"gender" public."gender" NULL,
	status public."userstatus" NULL,
	"type" public."usertype" NULL,
	CONSTRAINT tbl_user_pkey PRIMARY KEY (id),
	CONSTRAINT tbl_user_username_key UNIQUE (username)
);

CREATE TABLE public.tbl_group_has_user (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	group_id int4 NULL,
	user_id int8 NULL,
	CONSTRAINT tbl_group_has_user_pkey PRIMARY KEY (id)
);

ALTER TABLE public.tbl_group_has_user ADD CONSTRAINT fkk23xt6t0rhoc1s185sekeayf9 FOREIGN KEY (group_id) REFERENCES public.tbl_group(id);
ALTER TABLE public.tbl_group_has_user ADD CONSTRAINT fkqpbvdln7wyp9dnjvrx0mrrnk1 FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);


CREATE TABLE public.tbl_group (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	"role" int4 NULL,
	CONSTRAINT tbl_group_pkey PRIMARY KEY (id),
	CONSTRAINT ukh3fktf9o2h8xj1l22ytetwaok UNIQUE (role)
);
ALTER TABLE public.tbl_group ADD CONSTRAINT fkn60pk2rfas45nhvw3814kvwjg FOREIGN KEY ("role") REFERENCES public.tbl_role(id);

CREATE TABLE public.tbl_role (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT tbl_role_pkey PRIMARY KEY (id)
);


CREATE TABLE public.tbl_user_has_role (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	role_id int4 NULL,
	user_id int8 NULL,
	CONSTRAINT tbl_user_has_role_pkey PRIMARY KEY (id)
);

ALTER TABLE public.tbl_user_has_role ADD CONSTRAINT fklndw06guu8xedftiuosbtbr0a FOREIGN KEY (user_id) REFERENCES public.tbl_user(id);
ALTER TABLE public.tbl_user_has_role ADD CONSTRAINT fknbcb2rhv9gavk1vtounetntw0 FOREIGN KEY (role_id) REFERENCES public.tbl_role(id);

-- public.tbl_role_has_permission definition

-- Drop table

-- DROP TABLE public.tbl_role_has_permission;

CREATE TABLE public.tbl_role_has_permission (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	permission_id int4 NULL,
	role_id int4 NULL,
	CONSTRAINT tbl_role_has_permission_pkey PRIMARY KEY (id)
);

ALTER TABLE public.tbl_role_has_permission ADD CONSTRAINT fk7qnieb63nch1w822p22wu7il9 FOREIGN KEY (role_id) REFERENCES public.tbl_role(id);
ALTER TABLE public.tbl_role_has_permission ADD CONSTRAINT fkimpu2q9vas7utdl3gti0w2ied FOREIGN KEY (permission_id) REFERENCES public.tbl_permission(id);

CREATE TABLE public.tbl_permission (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	CONSTRAINT tbl_permission_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tbl_product (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	"name" varchar(255) NULL,
	category_id int8 NOT NULL,
	price numeric(19, 3) NULL,
	sku varchar(255) NULL,
	CONSTRAINT tbl_product_pkey PRIMARY KEY (id),
	CONSTRAINT ukdisju8p1ojkre4eo35l45mifl UNIQUE (sku)
);

ALTER TABLE public.tbl_product ADD CONSTRAINT fkfq7110lh85cseoy13cgni7pet FOREIGN KEY (category_id) REFERENCES public.tbl_category(id);

CREATE TABLE public.tbl_inventory (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	"location" varchar(255) NULL,
	quantity int8 NOT NULL,
	product_id int8 NOT NULL,
	discount int8 NULL,
	notes varchar(255) NULL,
	status varchar(255) NULL,
	CONSTRAINT tbl_inventory_pkey PRIMARY KEY (id)
);

ALTER TABLE public.tbl_inventory ADD CONSTRAINT fkrx0ob1tn2wn1j3s0y2f3v84w FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);

CREATE TABLE public.tbl_category (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT tbl_category_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tbl_category_attribute (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	category_id int8 NULL,
	description varchar(255) NULL,
	"name" varchar(255) NOT NULL,
	"options" jsonb NULL,
	required bool NOT NULL,
	"type" varchar(255) NOT NULL,
	CONSTRAINT tbl_category_attribute_pkey PRIMARY KEY (id),
	CONSTRAINT tbl_category_attribute_type_check CHECK (((type)::text = ANY ((ARRAY['TEXT'::character varying, 'NUMBER'::character varying, 'SELECT'::character varying, 'DATE'::character varying, 'BOOLEAN'::character varying])::text[])))
);

ALTER TABLE public.tbl_category_attribute ADD CONSTRAINT fkqu6usij2rpqsyk49ku2jlybwu FOREIGN KEY (category_id) REFERENCES public.tbl_category(id);

CREATE TABLE public.product_units (
	product_id int8 NOT NULL,
	unit_id int8 NOT NULL
);

ALTER TABLE public.product_units ADD CONSTRAINT fknhnb1fps3t9367u783cj5ipm FOREIGN KEY (product_id) REFERENCES public.tbl_product(id);
ALTER TABLE public.product_units ADD CONSTRAINT fko7qgs1e9ru837nred85gs7276 FOREIGN KEY (unit_id) REFERENCES public.tbl_unit(id);

CREATE TABLE public.tbl_unit (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	"name" varchar(255) NOT NULL,
	symbol varchar(255) NULL,
	CONSTRAINT tbl_unit_pkey PRIMARY KEY (id),
	CONSTRAINT uk7b1ffdbb6mopl4jcrs896mtmv UNIQUE (name)
);

CREATE TABLE public.tbl_order (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	order_date timestamp(6) NULL,
	payment_method public."_payment_method_enum" NULL,
	shipping_address varchar(255) NULL,
	status varchar(255) NULL,
	total_amount numeric(38, 2) NULL,
	user_id int8 NOT NULL,
	cancellation_reason varchar(255) NULL,
	cancelled_at timestamp(6) NULL,
	payment_id varchar(255) NULL,
	CONSTRAINT tbl_order_pkey PRIMARY KEY (id),
	CONSTRAINT tbl_order_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PROCESSING'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying, 'RETURNED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);

CREATE TABLE public.tbl_order_item (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	price numeric(38, 2) NULL,
	product_id int8 NULL,
	quantity int8 NULL,
	subtotal numeric(38, 2) NULL,
	order_id int8 NULL,
	CONSTRAINT tbl_order_item_pkey PRIMARY KEY (id)
);

ALTER TABLE public.tbl_order_item ADD CONSTRAINT fkmkqpajkg6p2wq4owcv1v08pc5 FOREIGN KEY (order_id) REFERENCES public.tbl_order(id);

CREATE TABLE public.tbl_payment (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	amount numeric(38, 2) NULL,
	currency varchar(255) NULL,
	transaction_id varchar(255) NULL,
	order_id varchar(255) NULL,
	payment_method int2 NULL,
	processed_at timestamp(6) NULL,
	refund_id bytea NULL,
	status int2 NULL,
	CONSTRAINT tbl_payment_payment_method_check CHECK (((payment_method >= 0) AND (payment_method <= 5))),
	CONSTRAINT tbl_payment_pkey PRIMARY KEY (id),
	CONSTRAINT tbl_payment_status_check CHECK (((status >= 0) AND (status <= 5)))
);

CREATE TABLE public.tbl_refund (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	amount numeric(38, 2) NULL,
	gateway_refund_id varchar(255) NULL,
	payment_id varchar(255) NULL,
	refunded_at timestamp(6) NULL,
	status int2 NULL,
	CONSTRAINT tbl_refund_pkey PRIMARY KEY (id),
	CONSTRAINT tbl_refund_status_check CHECK (((status >= 0) AND (status <= 2)))
);

CREATE TABLE public.tbl_address (
	address_type int4 NULL,
	created_at timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamp(6) NULL,
	user_id int8 NULL,
	apartment_number varchar(255) NULL,
	building varchar(255) NULL,
	city varchar(255) NULL,
	country varchar(255) NULL,
	floor varchar(255) NULL,
	street varchar(255) NULL,
	street_number varchar(255) NULL,
	CONSTRAINT tbl_address_pkey PRIMARY KEY (id)
);

INSERT INTO users (id, first_name, last_name, gender, date_of_birth, phone, email, username, password, type, status, created_at, updated_at) VALUES
(1, 'Nguyen', 'An', 'MALE', '1990-05-12', '0123456789', 'nguyen.an@email.com', 'nguyenan', 'password123', 'ADMIN', 'ACTIVE', '2024-01-01 10:00:00', '2024-01-01 10:00:00'),
(2, 'Tran', 'Bich', 'FEMALE', '1992-07-20', '0123456790', 'tran.bich@email.com', 'tranbich', 'password456', 'USER', 'ACTIVE', '2024-01-02 11:00:00', '2024-01-02 11:00:00'),
(3, 'Le', 'Cao', 'MALE', '1985-10-15', '0123456791', 'le.cao@email.com', 'lecao', 'password789', 'USER', 'INACTIVE', '2024-01-03 12:00:00', '2024-01-03 12:00:00'),
(4, 'Pham', 'Duy', 'MALE', '1988-03-05', '0123456792', 'pham.duy@email.com', 'phamduy', 'password321', 'ADMIN', 'ACTIVE', '2024-01-04 13:00:00', '2024-01-04 13:00:00'),
(5, 'Hoang', 'Thu', 'FEMALE', '1995-08-30', '0123456793', 'hoang.thu@email.com', 'hoangthu', 'password654', 'USER', 'ACTIVE', '2024-01-05 14:00:00', '2024-01-05 14:00:00'),
(6, 'Nguyen', 'Hieu', 'MALE', '1982-06-17', '0123456794', 'nguyen.hieu@email.com', 'nguyenhieu', 'password987', 'USER', 'ACTIVE', '2024-01-06 15:00:00', '2024-01-06 15:00:00'),
(7, 'Truong', 'My', 'FEMALE', '1993-01-11', '0123456795', 'truong.my@email.com', 'truongmy', 'password222', 'ADMIN', 'ACTIVE', '2024-01-07 16:00:00', '2024-01-07 16:00:00'),
(8, 'Vu', 'Duc', 'MALE', '1991-09-23', '0123456796', 'vu.duc@email.com', 'vuduc', 'password333', 'USER', 'INACTIVE', '2024-01-08 17:00:00', '2024-01-08 17:00:00'),
(9, 'Pham', 'Lan', 'FEMALE', '1996-12-02', '0123456797', 'pham.lan@email.com', 'phamlan', 'password444', 'ADMIN', 'ACTIVE', '2024-01-09 18:00:00', '2024-01-09 18:00:00'),
(10, 'Nguyen', 'Nhat', 'MALE', '1990-04-14', '0123456798', 'nguyen.nhat@email.com', 'nguyennhat', 'password555', 'USER', 'ACTIVE', '2024-01-10 19:00:00', '2024-01-10 19:00:00'),
(11, 'Mai', 'Thanh', 'FEMALE', '1987-02-22', '0123456799', 'mai.thanh@email.com', 'maithanh', 'password666', 'USER', 'ACTIVE', '2024-01-11 20:00:00', '2024-01-11 20:00:00'),
(12, 'Duong', 'Linh', 'FEMALE', '1992-11-17', '0123456800', 'duong.linh@email.com', 'duonglinh', 'password777', 'ADMIN', 'ACTIVE', '2024-01-12 21:00:00', '2024-01-12 21:00:00'),
(13, 'Bui', 'Hoang', 'MALE', '1994-01-07', '0123456801', 'bui.hoang@email.com', 'buihoang', 'password888', 'USER', 'INACTIVE', '2024-01-13 22:00:00', '2024-01-13 22:00:00'),
(14, 'Nguyen', 'Sang', 'MALE', '1984-10-10', '0123456802', 'nguyen.sang@email.com', 'nguyensang', 'password999', 'USER', 'ACTIVE', '2024-01-14 23:00:00', '2024-01-14 23:00:00'),
(15, 'Tran', 'Tuan', 'MALE', '1990-09-25', '0123456803', 'tran.tuan@email.com', 'trantuan', 'password112', 'ADMIN', 'ACTIVE', '2024-01-15 00:00:00', '2024-01-15 00:00:00'),
(16, 'Vo', 'Vinh', 'MALE', '1987-12-11', '0123456804', 'vo.vinh@email.com', 'vovinh', 'password223', 'USER', 'ACTIVE', '2024-01-16 01:00:00', '2024-01-16 01:00:00'),
(17, 'Luong', 'Tuyet', 'FEMALE', '1993-04-01', '0123456805', 'luong.tuyet@email.com', 'luongtuyet', 'password334', 'ADMIN', 'ACTIVE', '2024-01-17 02:00:00', '2024-01-17 02:00:00'),
(18, 'Chau', 'Tung', 'MALE', '1989-08-25', '0123456806', 'chau.tung@email.com', 'chautung', 'password445', 'USER', 'INACTIVE', '2024-01-18 03:00:00', '2024-01-18 03:00:00'),
(19, 'Nguyen', 'Cuong', 'MALE', '1997-05-05', '0123456807', 'nguyen.cuong@email.com', 'nguyencuong', 'password556', 'USER', 'ACTIVE', '2024-01-19 04:00:00', '2024-01-19 04:00:00'),
(20, 'Tran', 'Ngoc', 'FEMALE', '1998-12-30', '0123456808', 'tran.ngoc@email.com', 'tranngoc', 'password667', 'ADMIN', 'ACTIVE', '2024-01-20 05:00:00', '2024-01-20 05:00:00');
