spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  sendgrid:
    apiKey: ${SENDGRID_API_KEY}
    fromEmail: ${SENDGRID_FROM_EMAIL:candyyeukoi10@gmail.com}
    templateId: ${SENDGRID_TEMPLATE_ID:d-9a73652658ad43afb6b6c1ead33dc64f}
    verificationLink: ${SENDGRID_VERIFICATION_LINK:http://localhost:8080/user/confirm-email}
# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  secretKey: abc@123
  expiryMinutes: ${JWT_EXPIRY_MINUTES:60}
  expiryDay: ${JWT_EXPIRY_DAY:14}
  accessKey: ${JWT_ACCESS_KEY:peWSn9r50nTAGGq7VgxAtotK035+lqFr5VzoQfjR6vc=}
  refreshKey: ${JWT_REFRESH_KEY:zFmztGev7DOSya/6FDXl11q8yowVowgEsGanPVPN7G0=}